// quizzes/bpm-quiz.js
// Real-Life Thinking & Emotional Intelligence Quiz (Challenging Hinglish Version - 30 Questions)

window.bpmQuiz = [
  { question: "Agar tumhe lage ki teacher tumhe unfairly treat kar rahe hain, toh pehla step kya hoga?", options: ["Unhe ignore karna", "Seedha principal se complain karna", "Unse calmly baat karna"], answer: 2 },
  { question: "Agar koi friend tumse jhoot bolta pakda jaye, toh kya karoge?", options: ["Usse ignore kar doge", "Seedha usko jhoot ke liye insult kar doge", "Samajhne ki koshish karoge ki usne jhoot kyu bola"], answer: 2 },
  { question: "Kisi group project mein sab kaam tumhe karna pad raha hai, toh kya karoge?", options: ["Sabko bol doge ki tum kuch nahi karoge", "Apna best karoge aur baaki ko politely involve karne ki koshish karoge", "Teacher se complain kar doge"], answer: 1 },
  { question: "Agar tumhara close friend kisi aur ke saath zyada time spend karne lage, toh kya feel karoge?", options: ["Jealous", "Thoda ajeeb par normal", "Bohat gussa"], answer: 1 },
  { question: "Tumhe lagta hai tumhara talent log nahi dekh rahe, toh kya karna chahiye?", options: ["Complain karna", "Apne kaam ko aur visible banana", "Stop kar dena"], answer: 1 },
  { question: "Agar kisi ne tumhe insult kiya sabke saamne, toh kya karoge?", options: ["Wahin jawab doge", "Baad mein calmly baat karoge", "Andar hi andar hate karne lagoge"], answer: 1 },
  { question: "Tumhe kisi cheez ka fear hai, jaise stage pe bolne ka. Toh kya karna chahiye?", options: ["Avoid karna", "Practice karke slowly face karna", "Kisi aur se karwane kehna"], answer: 1 },
  { question: "Agar tumhara best friend exam mein cheat kar raha hai, toh kya karoge?", options: ["Ignore kar doge", "Teacher ko bata doge", "Usse baad mein honestly baat karoge"], answer: 2 },
  { question: "Kabhi kabhi tumhe kuch karne ka mann nahi karta, par karna zaroori hai. Tab kya karna chahiye?", options: ["Bas delay karna", "Thoda push karke start kar dena", "Completely skip kar dena"], answer: 1 },
  { question: "Agar kisi cheez mein tumhara opinion sabse alag hai, toh kya karna chahiye?", options: ["Chup rehna", "Apni baat respectfully rakhna", "Sabko galat sabit karna"], answer: 1 },
  { question: "Agar tum kisi competition mein haar jao, par sab keh rahe hain tum jeetne layak the, toh kya sochoge?", options: ["System galat hai", "Main next time aur better karunga", "Main kismat wala nahi hoon"], answer: 1 },
  { question: "Agar koi tumse rude ho, par tumhe uske sath kaam karna hai, toh kya karoge?", options: ["Usse rude hi rehna", "Professional aur calm rehna", "Avoid karna"], answer: 1 },
  { question: "Agar tum galti se kisi ka dil dukhado, toh kya karoge?", options: ["Ignore kar doge", "Apologize karke explain karoge", "Wait karoge wo khud theek ho jaye"], answer: 1 },
  { question: "Agar tum kisi group mein ho aur sab kisi ko bully kar rahe hain, toh kya karoge?", options: ["Saath doge taki alag na lago", "Mana kar doge aur stop karne ki koshish karoge", "Chup chap dekhta rahoge"], answer: 1 },
  { question: "Agar koi tumhe ignore karta rahe, toh kya karoge?", options: ["Usse bhi ignore karoge", "Poochega ki koi problem hai kya", "Zyada chipak jaoge"], answer: 1 },
  { question: "Agar kisi ne tumhe blame kiya bina reason, toh kya karna chahiye?", options: ["Wapas blame karna", "Shanti se apna point explain karna", "Usse baat band kar dena"], answer: 1 },
  { question: "Agar koi dost tumse secret share kare, par wo galat kaam kar raha hai, toh kya karoge?", options: ["Secret rakhoge", "Usse samjhaoge aur help karne ki koshish karoge", "Sabko bata doge"], answer: 1 },
  { question: "Tumhara ek friend hamesha negative baatein karta hai, toh kya karoge?", options: ["Usse dur rehna", "Try karna ki uska mood better ho", "Uski baatein sunke sad rehna"], answer: 1 },
  { question: "Agar koi tumhara idea copy karke credit le le, toh kya karoge?", options: ["Ladayi kar loge", "Sabke samne calmly apna version bataoge", "Chhod doge, next time better karoge"], answer: 1 },
  { question: "Agar tumhe lagta hai tumhe sab underestimate karte hain, toh kya karoge?", options: ["Prove karne ke liye overreact karna", "Apna kaam silently karte rehna", "Unhe ignore karna"], answer: 1 },
  { question: "Tumhe ek important kaam milta hai par tum confident nahi ho. Kya karoge?", options: ["Mana kar doge", "Seekh kar try karoge", "Kisi aur ko de doge"], answer: 1 },
  { question: "Agar kisi dost se ladai ho gayi aur dono galat hain, toh kya karna chahiye?", options: ["Usse ignore karna", "Pehle khud maafi maang lena", "Wait karna wo aaye"], answer: 1 },
  { question: "Tumhe koi pasand nahi karta, lekin tumhe uske sath project karna hai. Kya karoge?", options: ["Achi tarah kaam karoge bina dosti ki soch ke", "Bura behave karoge", "Kaam bigaad doge"], answer: 0 },
  { question: "Agar tumhe kisi ka success irritate kare, toh kya karoge?", options: ["Usse compare karte rahoge", "Apna focus apne goal pe rakhoge", "Uski burai karoge"], answer: 1 },
  { question: "Agar tumhe lagta hai tumhara opinion sunta koi nahi, toh kya karna chahiye?", options: ["Loud ho jana", "Apne words aur timing better karna", "Bura man jana"], answer: 1 },
  { question: "Kisi friend ne tumhe ignore kiya aur social media pe active hai, kya karoge?", options: ["Usse bhi ignore kar doge", "Seedha poochh loge kya problem hai", "Passive aggressive ho jaoge"], answer: 1 },
  { question: "Agar tumhe apne parents ke decision se problem ho, toh kya karoge?", options: ["Chillana", "Unse calmly baat karoge aur reason bataoge", "Mann mar ke maan jaoge"], answer: 1 },
  { question: "Agar tumhe kisi ne praise kiya jisme tumhara role chhota tha, toh kya sochoge?", options: ["Bas maza lo", "Sach batake honesty dikhana", "Sochna ki main deserve karta hoon sab"], answer: 1 },
  { question: "Agar kisi ne tumhare bare mein jhooti baat faila di, toh kya karoge?", options: ["Wapas uske bare mein jhoot faila doge", "Seedha usse baat karke clear karoge", "Sabko justify karte rahoge"], answer: 1 },
  { question: "Agar tumhara plan fail ho gaya, aur log hans rahe hain, toh kya karna chahiye?", options: ["Unse ladna", "Smile karke next time better karna", "Chhod dena"], answer: 1 }
];
